#!/usr/bin/env python3
"""Minimal privileged host helper for Aperyn.

Binds only to 127.0.0.1 and only manages an allow-list of Ollama performance
settings in a dedicated systemd drop-in. Authentication is a shared bearer
token generated by scripts/install-performance-helper.sh.
"""
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
import json, os, re, shlex, subprocess, tempfile, glob
from pathlib import Path

HOST='127.0.0.1'
PORT=int(os.environ.get('OLLAMA_CONTROL_HELPER_PORT','11436'))
TOKEN_FILE=Path(os.environ.get('OLLAMA_CONTROL_HELPER_TOKEN_FILE','/var/lib/ollama-control/helper.token'))
TOKEN=os.environ.get('OLLAMA_CONTROL_HELPER_TOKEN','')
if not TOKEN and TOKEN_FILE.is_file():
    TOKEN=TOKEN_FILE.read_text(encoding='utf-8').strip()
SERVICE=os.environ.get('OLLAMA_CONTROL_OLLAMA_SERVICE','ollama')
DROPIN=Path('/etc/systemd/system') / f'{SERVICE}.service.d' / '95-ollama-control.conf'
STATE=Path('/var/lib/ollama-control/settings.json')

ALLOW={
 'OLLAMA_FLASH_ATTENTION': ('bool', None),
 'OLLAMA_KV_CACHE_TYPE': ('enum', {'f16','q8_0','q4_0'}),
 'OLLAMA_NUM_PARALLEL': ('uint', (1,256)),
 'OLLAMA_MAX_LOADED_MODELS': ('uint', (0,256)),
 'OLLAMA_MAX_QUEUE': ('uint', (1,65536)),
 'OLLAMA_KEEP_ALIVE': ('duration', None),
 'OLLAMA_SCHED_SPREAD': ('bool', None),
 'OLLAMA_GPU_OVERHEAD': ('uint', (0, 2**63-1)),
 'OLLAMA_CONTEXT_LENGTH': ('uint', (0, 16_777_216)),
 'LLAMA_ARG_FIT': ('boolword', None),
 'LLAMA_ARG_FIT_TARGET': ('uint', (0, 1_048_576)),
 'OLLAMA_LOAD_TIMEOUT': ('duration', None),
 'OLLAMA_MAX_TRANSFER_STREAMS': ('uint', (1,256)),
}
DANGEROUS_MTP={'LLAMA_ARG_SPEC_TYPE','LLAMA_ARG_SPEC_DRAFT_N_MAX'}

def run(*args, timeout=15, check=True):
    return subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=check)



def _num(v):
    try: return float(str(v).strip().replace('W','').replace('C',''))
    except Exception: return None

def _nvidia_gpus():
    if not shutil_which('nvidia-smi'): return []
    fields='index,name,memory.total,memory.used,utilization.gpu,temperature.gpu,power.draw,power.limit'
    try:
        p=run('nvidia-smi',f'--query-gpu={fields}','--format=csv,noheader,nounits',timeout=4)
    except Exception:
        return []
    out=[]
    for line in p.stdout.splitlines():
        parts=[x.strip() for x in line.split(',')]
        if len(parts)<8: continue
        try:
            idx=int(parts[0]); total=int(float(parts[2])*1024*1024); used=int(float(parts[3])*1024*1024)
        except Exception: continue
        out.append({'index':idx,'name':parts[1],'total_bytes':total,'used_bytes':used,'free_bytes':max(0,total-used),
                    'utilization':_num(parts[4]),'temperature_c':_num(parts[5]),'power_w':_num(parts[6]),'power_limit_w':_num(parts[7]),'source':'nvidia-smi'})
    return out

def shutil_which(name):
    from shutil import which
    return which(name)

def _read_int(path):
    try: return int(Path(path).read_text().strip())
    except Exception: return None

def _amd_gpus():
    out=[]
    for card in sorted(glob.glob('/sys/class/drm/card[0-9]*')):
        dev=Path(card)/'device'
        total=_read_int(dev/'mem_info_vram_total')
        if not total: continue
        used=_read_int(dev/'mem_info_vram_used') or 0
        busy=_read_int(dev/'gpu_busy_percent')
        name='AMD GPU'
        try:
            vendor=(dev/'vendor').read_text().strip().lower()
            if vendor!='0x1002': continue
        except Exception: pass
        temp=None; power=None
        for hw in glob.glob(str(dev/'hwmon'/'hwmon*')):
            raw=_read_int(Path(hw)/'temp1_input')
            if raw is not None: temp=raw/1000.0; break
        for hw in glob.glob(str(dev/'hwmon'/'hwmon*')):
            raw=_read_int(Path(hw)/'power1_average')
            if raw is not None: power=raw/1_000_000.0; break
        out.append({'index':len(out),'name':name,'total_bytes':total,'used_bytes':used,'free_bytes':max(0,total-used),
                    'utilization':float(busy) if busy is not None else None,'temperature_c':temp,'power_w':power,'power_limit_w':None,'source':'amdgpu sysfs'})
    return out

def gpu_snapshot():
    gpus=_nvidia_gpus() or _amd_gpus()
    total=sum(int(g.get('total_bytes') or 0) for g in gpus)
    used=sum(int(g.get('used_bytes') or 0) for g in gpus)
    utils=[g.get('utilization') for g in gpus if g.get('utilization') is not None]
    return {'detected':bool(gpus),'devices':gpus,'total_bytes':total,'used_bytes':used,'free_bytes':max(0,total-used),
            'utilization':(sum(utils)/len(utils) if utils else None),'nvtop_installed':bool(shutil_which('nvtop'))}

def current_env():
    try:
        p=run('systemctl','show',SERVICE,'--property=Environment','--value',timeout=5)
        out={}
        for token in shlex.split(p.stdout.strip()):
            if '=' in token:
                k,v=token.split('=',1); out[k]=v
        return out
    except Exception:
        return {}

def active_state():
    try: return run('systemctl','is-active',SERVICE,timeout=4,check=False).stdout.strip()
    except Exception: return 'unknown'

def managed_state():
    try:
        data=json.loads(STATE.read_text())
        return data if isinstance(data,dict) else {}
    except Exception: return {}

def validate_value(key, value):
    if key not in ALLOW: raise ValueError(f'{key} is not allowed')
    if value is None or value=='': return None
    kind, arg=ALLOW[key]
    s=str(value).strip()
    if kind=='bool':
        if s.lower() not in {'true','false'}: raise ValueError(f'{key} must be true or false')
        return s.lower()
    if kind=='boolword':
        if s.lower() not in {'true','false','on','off','1','0'}: raise ValueError(f'{key} must be on/off')
        return 'on' if s.lower() in {'true','on','1'} else 'off'
    if kind=='enum':
        if s not in arg: raise ValueError(f'{key} must be one of {sorted(arg)}')
        return s
    if kind=='uint':
        try: n=int(s)
        except Exception: raise ValueError(f'{key} must be an integer')
        lo,hi=arg
        if n<lo or n>hi: raise ValueError(f'{key} must be between {lo} and {hi}')
        return str(n)
    if kind=='duration':
        if not re.fullmatch(r'-?\d+(?:\.\d+)?(?:ns|us|µs|ms|s|m|h)?',s):
            raise ValueError(f'{key} must be a duration such as 5m, 1h, 0, or -1')
        return s
    raise ValueError(f'Unsupported setting {key}')

def quote_env(s):
    return str(s).replace('\\','\\\\').replace('"','\\"')

def write_settings(values, clear_mtp=False):
    values={k:validate_value(k,v) for k,v in values.items() if k in ALLOW}
    lines=['# Managed by Aperyn. Manual edits may be overwritten.','[Service]']
    unset=[k for k,v in values.items() if v is None]
    if clear_mtp: unset += sorted(DANGEROUS_MTP)
    if unset: lines.append('UnsetEnvironment='+' '.join(sorted(set(unset))))
    for k in sorted(values):
        v=values[k]
        if v is not None: lines.append(f'Environment="{k}={quote_env(v)}"')
    DROPIN.parent.mkdir(parents=True,exist_ok=True)
    tmp=DROPIN.with_suffix('.tmp')
    tmp.write_text('\n'.join(lines)+'\n')
    os.chmod(tmp,0o644); os.replace(tmp,DROPIN)
    STATE.parent.mkdir(parents=True,exist_ok=True)
    STATE.write_text(json.dumps({'settings':values,'clear_mtp_globals':bool(clear_mtp)},indent=2)+'\n')
    os.chmod(STATE,0o600)
    run('systemctl','daemon-reload',timeout=15)
    run('systemctl','restart',SERVICE,timeout=45)
    return values

class Handler(BaseHTTPRequestHandler):
    server_version='OllamaControlHelper/1.1'
    def log_message(self, fmt, *args): pass
    def _json(self,status,obj):
        body=json.dumps(obj).encode(); self.send_response(status); self.send_header('Content-Type','application/json'); self.send_header('Content-Length',str(len(body))); self.end_headers(); self.wfile.write(body)
    def _auth(self):
        return bool(TOKEN) and self.headers.get('Authorization','')==f'Bearer {TOKEN}'
    def do_GET(self):
        if self.path=='/v1/ping': return self._json(200,{'ok':True,'service':SERVICE})
        if not self._auth(): return self._json(401,{'error':'unauthorized'})
        if self.path=='/v1/gpu': return self._json(200,gpu_snapshot())
        if self.path=='/v1/status':
            env=current_env(); state=managed_state()
            return self._json(200,{
                'installed':True,'service':SERVICE,'service_state':active_state(),
                'effective_env':{k:env.get(k) for k in sorted(ALLOW)},
                'managed':state.get('settings',{}),
                'conflicting_mtp_globals':{k:env.get(k) for k in DANGEROUS_MTP if env.get(k)},
                'dropin':str(DROPIN),
            })
        return self._json(404,{'error':'not found'})
    def do_POST(self):
        if not self._auth(): return self._json(401,{'error':'unauthorized'})
        if self.path!='/v1/apply': return self._json(404,{'error':'not found'})
        try:
            n=int(self.headers.get('Content-Length','0') or 0)
            if n>65536: return self._json(413,{'error':'payload too large'})
            data=json.loads(self.rfile.read(n) or b'{}')
            settings=data.get('settings') or {}
            if not isinstance(settings,dict): raise ValueError('settings must be an object')
            unknown=set(settings)-set(ALLOW)
            if unknown: raise ValueError('Unsupported settings: '+', '.join(sorted(unknown)))
            applied=write_settings(settings,bool(data.get('clear_mtp_globals')))
            env=current_env()
            return self._json(200,{'ok':True,'service_state':active_state(),'applied':applied,'effective_env':{k:env.get(k) for k in sorted(ALLOW)},'conflicting_mtp_globals':{k:env.get(k) for k in DANGEROUS_MTP if env.get(k)}})
        except subprocess.CalledProcessError as e:
            return self._json(500,{'error':(e.stderr or e.stdout or str(e)).strip()})
        except Exception as e:
            return self._json(400,{'error':str(e)})

if __name__=='__main__':
    if not TOKEN: raise SystemExit('OLLAMA_CONTROL_HELPER_TOKEN is required')
    ThreadingHTTPServer((HOST,PORT),Handler).serve_forever()
