import re, unittest
from html.parser import HTMLParser
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
class Parser(HTMLParser):
    def __init__(self): super().__init__(); self.refs=[]
    def handle_starttag(self,tag,attrs):
        values=dict(attrs)
        for key in ('src','href'):
            if values.get(key,'').startswith('/static/'): self.refs.append(values[key].split('?',1)[0].split('#',1)[0])
class StaticContractTests(unittest.TestCase):
    def test_templates_and_references(self):
        for template in (ROOT/'chat/templates').glob('*.html'):
            p=Parser(); p.feed(template.read_text(encoding='utf-8'))
            for ref in p.refs: self.assertTrue((ROOT/'chat/static'/ref.removeprefix('/static/')).exists(),f'{template}: {ref}')
    def test_pwa(self):
        sw=(ROOT/'chat/static/sw.js').read_text(); self.assertIn('aperyn-v1.27.3',sw); self.assertNotIn('22.0.0',sw)
        manifest=(ROOT/'chat/static/manifest.webmanifest').read_text(); self.assertIn('icon-192.png',manifest); self.assertIn('icon-512.png',manifest)
    def test_no_legacy_accent(self):
        bad=[]
        for path in list((ROOT/'chat/static').glob('*.css'))+list((ROOT/'chat/static').glob('*.js'))+list((ROOT/'chat/templates').glob('*.html')):
            if re.search(r'#67e8a5|#37c77f|rgba\(103\s*,\s*232\s*,\s*165',path.read_text(),re.I): bad.append(path.name)
        self.assertEqual(bad,[])
    def test_preview_sandbox(self): self.assertRegex((ROOT/'chat/templates/chat.html').read_text(),r'<iframe[^>]+sandbox="allow-scripts"')
    def test_navigation_layout_contract(self):
        theme=(ROOT/'chat/static/theme.css').read_text()
        chat=(ROOT/'chat/static/chat.css').read_text()
        manager=(ROOT/'chat/static/manager.css').read_text()
        self.assertIn('.icon-btn.mobile-menu{display:none',theme)
        self.assertIn('@media(max-width:820px){.icon-btn.mobile-menu{display:grid',theme)
        self.assertIn('.chat-sidebar{inset:14px auto 14px 14px;width:222px',chat)
        self.assertIn('@media(min-width:761px)',chat)
        self.assertIn('.chat-topbar .mobile-menu{display:none!important}',chat)
        self.assertIn('.chat-main{margin-left:250px}',chat)
        self.assertIn('.composer-wrap{left:250px}',chat)
        agent_polish=(ROOT/'chat/static/agent-v12415.css').read_text()
        self.assertIn('.agent-side-bottom .nav-icon{width:17px;height:17px;flex-basis:17px}',agent_polish)
        self.assertIn('@media(min-width:761px){.agent-side-bottom a{min-height:43px;padding:10px 12px;border-radius:14px}}',agent_polish)
        self.assertIn('.sidebar.app-sidebar{left:14px!important;right:auto!important;bottom:14px!important;width:222px!important',manager)
        self.assertIn('.topbar.app-topbar{height:auto!important;min-height:66px!important',manager)
    def test_selected_brand_asset(self):
        brand=ROOT/'chat/static/brand'
        source=(brand/'aperyn-mark.svg').read_text()
        self.assertIn('viewBox="0 0 64 64"',source)
        self.assertIn('Nym, the Aperyn signal moth',source)
        self.assertIn('M27 19C23 11 18 13 15 7',source)
        self.assertIn('fill-rule="evenodd"',source)
        self.assertNotIn('<image',source)
        self.assertNotRegex(source,r'\bhref=')
        self.assertFalse((brand/'ollama-control-mark.svg').exists())
        nym=(ROOT/'chat/static/nym.js').read_text()
        for state in ('idle','chatting','thinking','coding','approval','error'): self.assertIn(f"'{state}'",nym)
        self.assertIn('prefers-reduced-motion', (ROOT/'chat/static/theme.css').read_text())
    def test_theme_preset_range(self):
        template=(ROOT/'chat/templates/settings.html').read_text()
        script=(ROOT/'chat/static/settings.js').read_text()
        names=re.findall(r'data-preset="([a-z]+)"',template)
        self.assertEqual(len(names),12)
        self.assertEqual(len(names),len(set(names)))
        for name in names: self.assertRegex(script,rf'\b{name}:\{{accent:')
    def test_navigation_icon_family(self):
        sprite=(ROOT/'chat/static/brand/nav-icons.svg').read_text()
        names=('dashboard','models','chat','agent','library','storage','downloads','converter','settings')
        for name in names: self.assertIn(f'id="{name}"',sprite)
        self.assertEqual(sprite.count('<symbol '),len(names))
        for template in (ROOT/'chat/templates').glob('*.html'):
            source=template.read_text()
            if 'app-nav' in source or 'chat-side-bottom' in source or 'class="nav-item' in source:
                self.assertNotRegex(source,r'⌂ Dashboard|◫ (?:Installed models|Models)|◌ Chat|⌕ Model library|▤ Storage|⇣ Downloads|⇄ Dataset converter|⚙ Settings')
                self.assertIn('class="nav-icon"',source)
    def test_navigation_is_normalized_across_pages(self):
        theme=(ROOT/'chat/static/theme.js').read_text()
        agent=(ROOT/'chat/static/agent.js').read_text()
        expected=('dashboard','models','chat','agent','library','converter','storage','downloads','settings')
        self.assertIn('function normalizeNavigation()',theme)
        for item in expected: self.assertIn(f"['{item}'",theme)
        self.assertNotIn('normalizeAgentNavigation',agent)
    def test_managed_host_connector_contract(self):
        app=(ROOT/'chat/app.py').read_text(); connector=(ROOT/'host-connector/aperyn_host_connector.py').read_text(); settings=(ROOT/'chat/templates/settings.html').read_text()
        self.assertIn('CREATE TABLE IF NOT EXISTS managed_hosts',app)
        self.assertIn("'helper.status', 'helper.gpu', 'helper.apply'",app)
        self.assertIn("/api/host-connector/register",connector)
        self.assertNotIn('subprocess',connector)
        self.assertNotIn('import requests',connector)
        self.assertIn('Managed Ollama hosts',settings)
        self.assertTrue((ROOT/'host-connector/aperyn-host-connector.service').exists())
        self.assertTrue((ROOT/'scripts/install-host-connector.sh').exists())
    def test_host_runner_and_no_desktop_app(self):
        runner=(ROOT/'host-runner/aperyn_host_runner.py').read_text()
        client=(ROOT/'agent/host-tool').read_text()
        compose=(ROOT/'docker-compose.yml').read_text()
        self.assertFalse((ROOT/'desktop').exists())
        self.assertFalse((ROOT/'DESKTOP_APP.md').exists())
        self.assertFalse((ROOT/'.github/workflows/build-desktop.yml').exists())
        self.assertIn("'dotnet', 'cargo'", runner)
        self.assertIn("'python', 'python3'", runner)
        self.assertIn("'node', 'npm', 'npx'", runner)
        self.assertNotIn('shell=True', runner)
        self.assertNotIn('AF_INET', runner)
        self.assertIn('AF_UNIX', client)
        self.assertIn('/var/lib/aperyn-host-runner:/run/aperyn-host-runner', compose)
        self.assertNotIn('/var/run/docker.sock', compose)
        self.assertFalse((ROOT/'host-runner/aperyn-host-runner.socket').exists())
        self.assertIn('SOCKET_PATH = Path', runner)
        self.assertIn('socket.AF_UNIX, socket.SOCK_STREAM', runner)
    def test_chat_generation_metrics_and_context_layout(self):
        script=(ROOT/'chat/static/chat.js').read_text()
        style=(ROOT/'chat/static/chat.css').read_text()
        syntax=(ROOT/'chat/static/syntax.js').read_text()
        template=(ROOT/'chat/templates/chat.html').read_text()
        app=(ROOT/'chat/app.py').read_text()
        self.assertIn('setResponseMetrics',script)
        self.assertIn('d.eval_duration',script)
        self.assertIn('generated tokens',script)
        self.assertIn('grid-template-columns:max-content minmax(120px,180px)',style)
        self.assertIn('@media(min-width:761px){.code-preview-modal{display:flex',style)
        self.assertIn('width:min(1500px,calc(100vw - clamp(40px,6vw,96px)))',style)
        self.assertIn('.thinking-picker select option{background:var(--panel);color:var(--text)}',style)
        self.assertIn('output_tokens INTEGER NOT NULL DEFAULT 0',app)
        self.assertIn('eval_duration_ns INTEGER NOT NULL DEFAULT 0',app)
        self.assertIn("os.environ.get('OUTPUT_FOLDER', '/data/training')",app)
        self.assertIn("'Nym' if value in ('', 'AI')",app)
        self.assertIn("setNymState(ai,'thinking')",script)
        self.assertIn("setNymState(ai,'coding')",script)
        self.assertIn('expandedThinkingState',script)
        self.assertIn('thinkingWrap.open=Boolean(opts.thinkingOpen)',script)
        self.assertIn('/static/syntax.js',template)
        self.assertIn('AperynSyntax?.highlight',script)
        self.assertIn('renameChat',script)
        self.assertIn("return'javascript'",syntax)
        self.assertIn("return'keyword'",syntax)
    def test_github_container_release_contract(self):
        compose=(ROOT/'docker-compose.yml').read_text()
        launcher=(ROOT/'ollama-control').read_text()
        workflow=(ROOT/'.github/workflows/publish-container.yml').read_text()
        readme=(ROOT/'README.md').read_text()
        self.assertNotRegex(compose,r'(?m)^\s+build:')
        self.assertEqual(compose.count('ghcr.io/itzfrexite/aperyn-web:latest'),2)
        self.assertEqual(compose.count('pull_policy: always'),3)
        self.assertIn('ghcr.io/itzfrexite/aperyn-agent-runtime:latest',compose)
        agent_service=compose.split('\n  agent:',1)[1]
        self.assertNotRegex(agent_service,r'(?m)^\s+ports:')
        self.assertNotIn('/var/run/docker.sock',compose)
        self.assertNotIn('privileged:',compose)
        self.assertIn('${APERYN_AGENT_WORKSPACE:-${HOME}}:/workspace:ro',compose)
        self.assertIn('OPENCODE_WORKSPACE_DISPLAY: ${APERYN_AGENT_WORKSPACE:-${HOME}}',compose)
        self.assertIn('${APERYN_AGENT_MNT:-/mnt}:/mnt:ro',compose)
        self.assertIn('${APERYN_AGENT_MNT:-/mnt}:/mnt',compose)
        self.assertIn('OPENCODE_MNT_DISPLAY: ${APERYN_AGENT_MNT:-/mnt}',compose)
        self.assertNotIn('--build',launcher)
        self.assertIn("legacy = 'OLLAMA_CONTROL_IMAGE=ollama-control:local'",launcher)
        self.assertIn("ghcr.io/itzfrexite/aperyn-web:latest",launcher)
        self.assertIn('packages: write',workflow)
        self.assertIn('context: ./chat',workflow)
        self.assertIn('context: ./agent',workflow)
        self.assertIn('github.com/manzolo/ollama-model-train-guide',readme)
        self.assertIn('github.com/ollama-admin/ollama-admin',readme)
    def test_single_current_release_notes(self):
        notes=sorted(ROOT.glob('RELEASE_NOTES*'))
        self.assertEqual([p.name for p in notes],['RELEASE_NOTES_V1.27.3.md'])
        source='\n'.join(p.read_text() for p in (ROOT/'chat/static').glob('*.css'))
        self.assertNotRegex(source,r'(?<![.\d])v(?:[1-9]|1\d|2[0-3])(?=[^.\d]|$)')
    def test_agent_ui_and_runtime_contract(self):
        template=(ROOT/'chat/templates/agent.html').read_text()
        script=(ROOT/'chat/static/agent.js').read_text()
        style=(ROOT/'chat/static/agent.css').read_text()
        gateway=(ROOT/'chat/agent_gateway.py').read_text()
        runtime=(ROOT/'agent/entrypoint.sh').read_text()
        self.assertIn('id="agentAttention"',template)
        self.assertIn('id="agentContext"',template)
        self.assertIn('Model context',template)
        self.assertIn('configured_context=',runtime)
        self.assertIn('id="workspaceDialogBackdrop"',template)
        self.assertIn('/api/agent/workspaces',script)
        self.assertIn('syncAgentViewport',script)
        self.assertIn('--agent-vv-height',style)
        self.assertIn('renameAgent',script)
        self.assertIn('websearch: "allow"',runtime)
        self.assertIn('/static/icons/icon-192.png',template)
        self.assertIn('/static/nym.js',template)
        self.assertIn('safe_workspace',gateway)
        self.assertIn('id="todoList"',template)
        self.assertIn('prompt_async',gateway)
        self.assertIn("user.get('role') == 'admin'",gateway)
        self.assertIn('data-permission',script)
        self.assertIn('data-question',script)
        self.assertIn('snapshot',script)
        self.assertIn('renderContext',script)
        self.assertIn('nearBottom',script)
        self.assertIn('scrollLatest=true',script)
        self.assertIn('reported_total',gateway)
        self.assertIn('zero-filled token object',gateway)
        self.assertIn('/static/syntax.js',template)
        self.assertIn('renderAgentMarkdown',script)
        self.assertIn('renderWorkingIndicator',script)
        self.assertIn('messageHasVisibleAgentContent',script)
        self.assertIn('pendingAssistantSegment',script)
        self.assertIn('showPlaceholder=Boolean(pending)',script)
        chat_css=(ROOT/'chat/static/chat.css').read_text()
        self.assertIn("content:'Nym is thinking'",chat_css)
        self.assertIn('chatWorkingDots',chat_css)
        self.assertIn("reasoningLive=live==='busy'",script)
        self.assertIn('?850:5000',script)
        self.assertIn('.agent-working',style)
        self.assertIn('.agent-code-block',style)
        self.assertIn('agentMessageKey',script)
        self.assertIn('.agent-reasoning[open]',script)
        self.assertIn('id="diffViewerBackdrop"',template)
        self.assertIn('id="diffViewerCode"',template)
        self.assertIn('renderChangesSummary',script)
        self.assertIn('renderPatch',script)
        self.assertIn('renderFileContents',script)
        self.assertIn('data-view-diff',script)
        self.assertIn('data-change-group',script)
        self.assertIn('lastForGroup',script)
        self.assertIn('change_groups',gateway)
        self.assertIn("status==='added'?'add':'context'",script)
        self.assertIn("status==='deleted'?'remove':'context'",script)
        self.assertIn('5000',script)
        self.assertIn('.agent-change-summary',style)
        self.assertIn('.diff-code-row',style)
        self.assertIn('Follow-up queued',script)
        self.assertIn("connected?'Ready':'Unavailable'",script)
        self.assertIn('toolTarget',script)
        self.assertIn('approvalMode',script)
        self.assertIn('installNotificationControl',script)
        self.assertIn('workspace-folder-icon',script)
        self.assertIn('APERYN_AGENT_CONTEXT_LIMIT',runtime)
        self.assertIn('architecture_context',runtime)
        self.assertIn('approval_mode',gateway)
        self.assertIn('child_response',gateway)
        self.assertIn("stop=activeState(liveState)&&!hasText",script)
        self.assertIn('agent-session-status',style)
        self.assertIn("'completed'",gateway)
        self.assertIn("'waiting'",gateway)
        self.assertIn("'@mnt'",gateway)
        self.assertIn('.activity-panel',style)
        self.assertIn('OPENCODE_SERVER_PASSWORD',runtime)
        self.assertIn('external_directory: "deny"',runtime)
        self.assertIn('"ls *": "allow"',runtime)
        self.assertIn('"*": "ask"',runtime)
        self.assertIn('/api/show',runtime)
        self.assertIn('aperyn_context',runtime)
        self.assertIn('limit: {context:',runtime)
        for protected in ('.ssh', '.gnupg', '.aws', '.kube', '.docker', '.config/gh', '.netrc'):
            self.assertIn(protected,runtime)
        self.assertNotIn('docker.sock',runtime)
    def test_dashboard_telemetry_clear_contract(self):
        template=(ROOT/'chat/templates/manager.html').read_text()
        script=(ROOT/'chat/static/manager.js').read_text()
        style=(ROOT/'chat/static/manager.css').read_text()
        app=(ROOT/'chat/app.py').read_text()
        proxy=(ROOT/'chat/proxy.py').read_text()
        self.assertIn('id="clearTelemetryModal"',template)
        self.assertIn('id="confirmClearTelemetry"',template)
        self.assertIn('Clear dashboard data',template)
        self.assertGreater(template.index('dashboard-data-actions-bottom'),template.index('id="recentRequests"'))
        self.assertIn("api('/api/manager/telemetry',{method:'DELETE'})",script)
        self.assertIn('.dashboard-clear',style)
        self.assertIn("@app.delete('/api/manager/telemetry')",app)
        self.assertIn("user.get('role') != 'admin'",app)
        self.assertIn("@proxy_app.post('/__ollama_control/live/clear')",proxy)
        self.assertIn('_telemetry_clear_identity()',app)
        self.assertIn('core._telemetry_clear_identity()',proxy)
        self.assertIn('active_generations_preserved',proxy)
    def test_external_provider_security_contract(self):
        app=(ROOT/'chat/app.py').read_text(); store=(ROOT/'chat/provider_store.py').read_text(); settings=(ROOT/'chat/templates/settings.html').read_text(); compose=(ROOT/'docker-compose.yml').read_text()
        self.assertIn('id="providerConnections"',settings)
        self.assertIn("Fernet",store); self.assertIn("provider-secrets.key",store)
        self.assertIn("https://api.openai.com/v1",store); self.assertIn("https://api.anthropic.com/v1",store); self.assertIn("https://generativelanguage.googleapis.com/v1beta",store)
        self.assertNotIn("base_url = str(",store)
        self.assertIn("@app.put('/api/providers/<provider>')",app)
        self.assertIn('APERYN_AGENT_UID',compose)
if __name__=='__main__': unittest.main()
